# Generated by Django 5.2.11 on 2026-02-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('quote', models.CharField(max_length=20)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='testimonials/images')),
            ],
        ),
    ]
