# Generated by Django 5.2.11 on 2026-02-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='quote',
            field=models.CharField(max_length=500),
        ),
    ]
